### ISSUE TITLE
Project ideas

### ISSUE THREAD

**Issue by nygeog** [pratt-savi-810/pratt-savi-810.github.io#1]
Write out the project idea.

**Comment by kejoseph90** [comment]
Hi Danny, 

So I thought of a potential project idea that I would like to further develop in this course. 

One of my annual projects at NYC Small Business Services is determining whether or not grant applicants for our AvenueNYC program are in CDBG eligible communities. Due to the nature of our grant funding which are provided by HUD. 

Every year groups propose a commercial revitalization project and specify the boundaries (site) for which they will be implementing the project. My job is to:
1) Create a shapefile of the study area
2) Overlay it with the CDBG eligibility census tract shapefile
3) Draw a .75 mile (.75 outer boroughs, .25 for Manhattan) buffer using the study are as a shape
4) Determine whether 50% or more of the tracts within the buffer falls within in CDBG eligible tract

I do this for about 70-100 applicants across the five boroughs. I attached a copy of what these simple maps look like to give you an idea of how this all plays out graphically. 
[CCI_AveNYC_FY17.pdf](https://github.com/pratt-savi-810/pratt-savi-810.github.io/files/1419375/CCI_AveNYC_FY17.pdf)
[UPROSE_AveNYC_FY17.pdf](https://github.com/pratt-savi-810/pratt-savi-810.github.io/files/1419376/UPROSE_AveNYC_FY17.pdf)

**Comment by nygeog** [comment]
@kejoseph90 THANKS!!! repointing to this thread and repo: https://github.com/pratt-savi-810/project-kejoseph90/issues/1
